[project]
name = "apollo-mcp-graphql-experiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.0",
    "httpx>=0.28.1",
]
